### ISSUE TITLE
Geo extra information ../ext_data/geo_stuff.zip

### ISSUE THREAD

**Issue by truetqy** [alexeygrigorev/avito-duplicates-kaggle#2]
Hi ~ Is it possible to share your ext_data on geo feature? 
Thanks a lot ~

**Comment by alexeygrigorev** [comment]
You can download it from https://github.com/alexeygrigorev/avito-duplicates-kaggle/blob/master/ext_data/geo_stuff.zip
I also modified `mongo_put_iteminfo.py` so it reads the file from that location.

**Comment by dansonc** [comment]
Hi, could you upload the 'signatures.bin', which is read in the file 'prepare_image_hashes.py'?
Thank you very much.

**Comment by alexeygrigorev** [comment]
This one won't be possible to put on github as it's quite large. Can you recommend a file hosting?

**Comment by dansonc** [comment]
Could you upload it to a google drive or dropbox? Thank you.

**Comment by dansonc** [comment]
Or maybe you can try the skydrive, it also offers 15gb free space.

**Comment by alexeygrigorev** [comment]
[image-signatures.bin](https://mega.nz/#!EI1QGSqR!BdgyZUq3cXTCkdMtRuU_sI0aefKD5V_gbIqlnEFp-hA) let me know if the link doesn't work

**Comment by dansonc** [comment]
I have downloaded it, thank you very much.
